"""
AI Analysis Simulation for Genre Comparison — MPGM
=====================================================
Generates a natural-language "analyst report" comparing two genres, plus
Excel and PDF exports of that report.

Important honesty note: this is a DETERMINISTIC, RULE-BASED narrative
generator — not a live call to an LLM API. It was built this way on
purpose: MPGM's entire architecture is free-to-run (Streamlit Community
Cloud + GitHub Actions, no paid services), and a live LLM call would
require an API key and a per-request cost that breaks that promise, plus
a live web app calling a third-party LLM on every click introduces a
dependency that can silently fail. Every number in the report is computed
directly from the same cleaned dataset and the same statistical tests
already used elsewhere in the app (Mann-Whitney U from dunn_posthoc where
available) — nothing here is generated by a model or invented. The report
is presented to the user as a "simulation" for exactly this reason: it
reads like an analyst's summary, but it's arithmetic and template text,
not inference from a language model.
"""

import io
from datetime import datetime, timezone

import pandas as pd


def _pct_diff(a: float, b: float) -> float:
    """Percentage difference of a relative to b. Returns 0 if b is 0/NaN."""
    if b is None or pd.isna(b) or b == 0:
        return 0.0
    return (a - b) / abs(b) * 100.0


def compute_comparison_metrics(df_a: pd.DataFrame, df_b: pd.DataFrame) -> dict:
    """Raw numeric metrics for both genres, used both for the display table
    and as the arithmetic basis for the narrative report."""
    def block(d):
        return {
            "n": len(d),
            "avg_rating": d["Rating_num"].mean(),
            "median_installs": d["Installs_num"].median(),
            "avg_reviews": d["Reviews_num"].mean(),
            "avg_size": d["Size_MB"].mean(),
            "paid_share": (d["Price_num"] > 0).mean(),
            "avg_popularity": d["Popularity_Score"].mean(),
        }
    return {"a": block(df_a), "b": block(df_b)}


def _find_pairwise_test(posthoc_df: pd.DataFrame, genre_a: str, genre_b: str):
    """Look up the precomputed Mann-Whitney U + Bonferroni result for this
    exact genre pair from dunn_posthoc's full output, if it exists there
    (dunn_posthoc only includes genres with n>=5 on each side)."""
    if posthoc_df is None or posthoc_df.empty:
        return None
    match = posthoc_df[
        ((posthoc_df["genre_1"] == genre_a) & (posthoc_df["genre_2"] == genre_b)) |
        ((posthoc_df["genre_1"] == genre_b) & (posthoc_df["genre_2"] == genre_a))
    ]
    if match.empty:
        return None
    row = match.iloc[0]
    return {"u_statistic": row["u_statistic"], "p_bonferroni": row["p_bonferroni"],
            "significant": bool(row["significant"])}


_METRIC_META = {
    "avg_rating": {"en": "average rating", "tr": "ortalama puan", "higher_better": True, "fmt": "{:.2f}"},
    "median_installs": {"en": "median installs", "tr": "medyan kurulum", "higher_better": True, "fmt": "{:,.0f}"},
    "avg_reviews": {"en": "average review count", "tr": "ortalama yorum sayısı", "higher_better": True, "fmt": "{:,.0f}"},
    "avg_size": {"en": "average app size", "tr": "ortalama uygulama boyutu", "higher_better": None, "fmt": "{:.1f} MB"},
    "paid_share": {"en": "share of paid apps", "tr": "ücretli uygulama oranı", "higher_better": None, "fmt": "{:.0%}"},
    "avg_popularity": {"en": "average popularity score", "tr": "ortalama popülerlik skoru", "higher_better": True, "fmt": "{:.2f}"},
}


def generate_comparison_narrative(genre_a: str, genre_b: str, label_a: str, label_b: str,
                                   metrics: dict, posthoc_df: pd.DataFrame = None, lang: str = "en") -> str:
    """Builds the multi-paragraph "AI analyst" narrative. Every sentence
    traces back to a number in `metrics` or the pairwise test lookup."""
    a, b = metrics["a"], metrics["b"]
    lines = []

    if lang == "tr":
        lines.append(f"## Karşılaştırma Özeti: {label_a} vs {label_b}")
        lines.append(
            f"Bu rapor, {a['n']} adet {label_a} oyunu ile {b['n']} adet {label_b} oyununun "
            f"temizlenmiş Google Play verisine dayanarak karşılaştırmasıdır."
        )
    else:
        lines.append(f"## Comparison Summary: {label_a} vs {label_b}")
        lines.append(
            f"This report compares {a['n']} {label_a} games against {b['n']} {label_b} games "
            f"using the cleaned Google Play dataset."
        )

    # Per-metric narrative
    a_wins, b_wins = 0, 0
    for key, meta in _METRIC_META.items():
        va, vb = a[key], b[key]
        if pd.isna(va) or pd.isna(vb):
            continue
        diff_pct = _pct_diff(va, vb)
        name = meta[lang]
        fmt = meta["fmt"]
        if meta["higher_better"] is None:
            if lang == "tr":
                lines.append(f"- **{name.capitalize()}**: {label_a} {fmt.format(va)}, {label_b} {fmt.format(vb)}.")
            else:
                lines.append(f"- **{name.capitalize()}**: {label_a} {fmt.format(va)}, {label_b} {fmt.format(vb)}.")
            continue
        leader = label_a if va > vb else label_b
        if va > vb:
            a_wins += 1
        elif vb > va:
            b_wins += 1
        if lang == "tr":
            lines.append(
                f"- **{name.capitalize()}**: {label_a} {fmt.format(va)}, {label_b} {fmt.format(vb)} "
                f"— {leader} yaklaşık %{abs(diff_pct):.0f} daha yüksek."
            )
        else:
            lines.append(
                f"- **{name.capitalize()}**: {label_a} {fmt.format(va)}, {label_b} {fmt.format(vb)} "
                f"— {leader} is roughly {abs(diff_pct):.0f}% higher."
            )

    # Statistical significance, if we have it precomputed
    test = _find_pairwise_test(posthoc_df, genre_a, genre_b)
    if test is not None:
        if lang == "tr":
            verdict = (
                f"İstatistiksel olarak, bu iki tür arasındaki puan farkı Mann-Whitney U testine göre "
                f"anlamlıdır (U={test['u_statistic']:.0f}, Bonferroni-düzeltmeli p={test['p_bonferroni']:.4f})."
                if test["significant"] else
                f"İstatistiksel olarak, bu iki tür arasındaki puan farkı Mann-Whitney U testine göre "
                f"anlamlı DEĞİLDİR (U={test['u_statistic']:.0f}, Bonferroni-düzeltmeli p={test['p_bonferroni']:.4f})."
            )
        else:
            verdict = (
                f"Statistically, the rating difference between these two genres IS significant per "
                f"the Mann-Whitney U test (U={test['u_statistic']:.0f}, Bonferroni-corrected p={test['p_bonferroni']:.4f})."
                if test["significant"] else
                f"Statistically, the rating difference between these two genres is NOT significant per "
                f"the Mann-Whitney U test (U={test['u_statistic']:.0f}, Bonferroni-corrected p={test['p_bonferroni']:.4f})."
            )
        lines.append("")
        lines.append(verdict)
    else:
        note = ("Not: bu tür çifti için önceden hesaplanmış bir anlamlılık testi mevcut değil "
                "(en az bir tür 5'ten az örneğe sahip olabilir)." if lang == "tr" else
                "Note: no precomputed significance test is available for this genre pair "
                "(one side may have fewer than 5 samples).")
        lines.append("")
        lines.append(note)

    # Overall verdict
    lines.append("")
    if lang == "tr":
        lines.append("### Genel Değerlendirme")
        if a_wins > b_wins:
            lines.append(
                f"Ölçülen metriklerin çoğunda ({a_wins}/{a_wins + b_wins}) **{label_a}** öne çıkıyor. "
                f"Bu, {label_a} türünün genel olarak daha güçlü pazar performansı gösterdiğine işaret eder — "
                f"ancak bu bir kesinlik değil, göreli bir eğilimdir."
            )
        elif b_wins > a_wins:
            lines.append(
                f"Ölçülen metriklerin çoğunda ({b_wins}/{a_wins + b_wins}) **{label_b}** öne çıkıyor. "
                f"Bu, {label_b} türünün genel olarak daha güçlü pazar performansı gösterdiğine işaret eder — "
                f"ancak bu bir kesinlik değil, göreli bir eğilimdir."
            )
        else:
            lines.append(f"İki tür, ölçülen metrikler arasında dengeli bir görünüm sergiliyor ({a_wins}-{b_wins}).")
        lines.append(
            "\n*Bu rapor kural-tabanlı bir simülasyon ile otomatik üretilmiştir — canlı bir yapay zeka "
            "modeli çağrısı içermez. Tüm sayılar gerçek, temizlenmiş veri setinden doğrudan hesaplanmıştır.*"
        )
    else:
        lines.append("### Overall Verdict")
        if a_wins > b_wins:
            lines.append(
                f"**{label_a}** leads on most measured metrics ({a_wins}/{a_wins + b_wins}), suggesting "
                f"generally stronger market performance overall — this is a relative tendency, not a certainty."
            )
        elif b_wins > a_wins:
            lines.append(
                f"**{label_b}** leads on most measured metrics ({b_wins}/{a_wins + b_wins}), suggesting "
                f"generally stronger market performance overall — this is a relative tendency, not a certainty."
            )
        else:
            lines.append(f"The two genres show a balanced picture across measured metrics ({a_wins}-{b_wins}).")
        lines.append(
            "\n*This report was auto-generated by a rule-based simulation — it does not call a live AI "
            "model. Every figure is computed directly from the real, cleaned dataset.*"
        )

    return "\n".join(lines)


def build_excel_report(label_a: str, label_b: str, comparison_table: pd.DataFrame,
                        narrative: str, lang: str = "en") -> bytes:
    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine="openpyxl") as writer:
        comparison_table.to_excel(writer, sheet_name="Comparison" if lang == "en" else "Karsilastirma", index=False)
        narrative_lines = [ln for ln in narrative.replace("**", "").replace("##", "").replace("###", "").split("\n")]
        narrative_df = pd.DataFrame({"Report" if lang == "en" else "Rapor": narrative_lines})
        narrative_df.to_excel(writer, sheet_name="AI Report" if lang == "en" else "AI Raporu", index=False)

        for sheet in writer.sheets.values():
            sheet.column_dimensions["A"].width = 42
            sheet.column_dimensions["B"].width = 22
            sheet.column_dimensions["C"].width = 22
    return buf.getvalue()


def build_pdf_report(label_a: str, label_b: str, comparison_table: pd.DataFrame,
                      narrative: str, lang: str = "en") -> bytes:
    import os
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    # Register a bundled Unicode font (DejaVu Sans) so Turkish characters
    # (ş, ı, ğ, ü, ö, ç, İ, Ğ, Ş, Ö, Ç, Ü) render correctly. ReportLab's
    # built-in fonts (Helvetica etc.) only cover Latin-1 and silently
    # replace unsupported characters with "■", which is what happened
    # before this fix. The font is bundled in assets/fonts/ so this works
    # identically on any deployment (Streamlit Cloud's server has no
    # guarantee of any particular system font being installed).
    FONT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets", "fonts")
    font_regular = "Helvetica"
    font_bold = "Helvetica-Bold"
    font_italic = "Helvetica-Oblique"
    try:
        pdfmetrics.registerFont(TTFont("DejaVu", os.path.join(FONT_DIR, "DejaVuSans.ttf")))
        pdfmetrics.registerFont(TTFont("DejaVu-Bold", os.path.join(FONT_DIR, "DejaVuSans-Bold.ttf")))
        pdfmetrics.registerFont(TTFont("DejaVu-Oblique", os.path.join(FONT_DIR, "DejaVuSans-Oblique.ttf")))
        font_regular, font_bold, font_italic = "DejaVu", "DejaVu-Bold", "DejaVu-Oblique"
    except Exception:
        pass  # Falls back to Helvetica (Latin-1 only) if the bundled font is missing for any reason.

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=1.5 * cm, bottomMargin=1.5 * cm,
                             leftMargin=1.7 * cm, rightMargin=1.7 * cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleMPGM", parent=styles["Title"], fontName=font_bold,
                                  textColor=colors.HexColor("#0F6E56"))
    body_style = ParagraphStyle("BodyMPGM", parent=styles["BodyText"], fontName=font_regular,
                                 fontSize=10, leading=14, spaceAfter=6)
    body_italic_style = ParagraphStyle("BodyItalicMPGM", parent=body_style, fontName=font_italic)
    h2_style = ParagraphStyle("H2MPGM", parent=styles["Heading2"], fontName=font_bold,
                               textColor=colors.HexColor("#0F6E56"))

    title = f"MPGM — {label_a} vs {label_b}" if lang == "en" else f"MPGM — {label_a} vs {label_b} Karşılaştırma Raporu"
    story = [Paragraph(title, title_style), Spacer(1, 0.4 * cm)]

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    gen_label = "Generated" if lang == "en" else "Oluşturulma"
    story.append(Paragraph(f"<i>{gen_label}: {generated_at}</i>", body_style))
    story.append(Spacer(1, 0.3 * cm))

    # Table
    table_data = [list(comparison_table.columns)] + comparison_table.astype(str).values.tolist()
    tbl = Table(table_data, hAlign="LEFT")
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#5FE0C7")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#0B1220")),
        ("FONTNAME", (0, 0), (-1, 0), font_bold),
        ("FONTNAME", (0, 1), (-1, -1), font_regular),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F1F5F9")]),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(tbl)
    story.append(Spacer(1, 0.6 * cm))

    # Narrative — render markdown-ish text as paragraphs
    for line in narrative.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.15 * cm))
            continue
        if line.startswith("## "):
            story.append(Paragraph(line[3:], h2_style))
        elif line.startswith("### "):
            story.append(Paragraph(f"<b>{line[4:]}</b>", body_style))
        elif line.startswith("- "):
            clean = line[2:]
            # bold **text** -> <b>text</b>
            parts = clean.split("**")
            rendered = ""
            for i, part in enumerate(parts):
                rendered += f"<b>{part}</b>" if i % 2 == 1 else part
            story.append(Paragraph(f"• {rendered}", body_style))
        elif line.startswith("*") and line.endswith("*"):
            story.append(Paragraph(line.strip("*"), body_italic_style))
        else:
            parts = line.split("**")
            rendered = ""
            for i, part in enumerate(parts):
                rendered += f"<b>{part}</b>" if i % 2 == 1 else part
            story.append(Paragraph(rendered, body_style))

    doc.build(story)
    return buf.getvalue()
